version: '3.8'

#volumes:
#  metadata_data: {}
#  middle_var: {}
#  historical_var: {}
#  broker_var: {}
#  coordinator_var: {}
#  router_var: {}
#  druid_shared: {}

services:
  s3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.minio
    container_name: "s3"
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
#  postgres:
#    container_name: postgres
#    image: postgres:latest
#    volumes:
#      - metadata_data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=FoolishPasswords
#      - POSTGRES_USER=druid
#      - POSTGRES_DB=druid
#
#  # Need 3.5 or later for container nodes
#  zookeeper:
#    container_name: zookeeper
#    image: zookeeper:3.5
#    ports:
#      - "2181:2181"
#    environment:
#      - ZOO_MY_ID=1
#
#  coordinator:
#    image: apache/druid:0.21.1
#    container_name: coordinator
#    volumes:
#      - druid_shared:/opt/shared
#      - coordinator_var:/opt/druid/var
#    depends_on:
#      - zookeeper
#      - postgres
#    ports:
#      - "8081:8081"
#    command:
#      - coordinator
#    env_file:
#      - .env
#
#  broker:
#    image: apache/druid:0.21.1
#    container_name: broker
#    volumes:
#      - broker_var:/opt/druid/var
#    depends_on:
#      - zookeeper
#      - postgres
#      - coordinator
#    ports:
#      - "8082:8082"
#    command:
#      - broker
#    env_file:
#      - .env
#
#  historical:
#    image: apache/druid:0.21.1
#    container_name: historical
#    volumes:
#      - druid_shared:/opt/shared
#      - historical_var:/opt/druid/var
#    depends_on:
#      - zookeeper
#      - postgres
#      - coordinator
#    ports:
#      - "8083:8083"
#    command:
#      - historical
#    env_file:
#      - .env
#
#  middlemanager:
#    image: apache/druid:0.21.1
#    container_name: middlemanager
#    volumes:
#      - druid_shared:/opt/shared
#      - middle_var:/opt/druid/var
#    depends_on:
#      - zookeeper
#      - postgres
#      - coordinator
#    ports:
#      - "8091:8091"
#      - "8100-8105:8100-8105"
#    command:
#      - middleManager
#    env_file:
#      - .env
#
#  router:
#    image: apache/druid:0.21.1
#    container_name: router
#    volumes:
#      - router_var:/opt/druid/var
#    depends_on:
#      - zookeeper
#      - postgres
#      - coordinator
#    ports:
#      - "8888:8888"
#    command:
#      - router
#    env_file:
#      - .env
